version: "3.9"
services:
  haproxy:
    build: ./haproxy
    image: "haproxy-docker-logging:1.8.31"
    ports:
      - "8080:80"
      - "8090:8090"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    links:
      - server:legacy_server
  server:
    image: "httpd:2.4"
    volumes:
      - ./server:/usr/local/apache2/htdocs/
